### ISSUE TITLE
Some examples

### ISSUE THREAD

**Issue by meesrutten** [darkroomengineering/tempus#1]
Hi SF, love you guys :)

Since there are some default lots of people use, it might be nice to add those to the readme or an examples md file.

Something like:

## GSAP
```
  gsap.ticker.remove(gsap.updateRoot);
  raf.add((time: number) => {
    gsap.updateRoot(time / 1000);
  }, 0);
```

## Lenis
```
    const lenisRaf = raf.add((time: number) => {
      lenis.raf(time);
    }, 0);
```

**Comment by clementroche** [comment]
Just added those examples, thnak you @meesrutten
